name: CI + Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit and integration tests
        run: |
          PYTHONPATH=src pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.13.0
        with:
          minikube version: 'v1.36.0'
          kubernetes version: 'v1.32.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker

      - name: Use Minikube Docker daemon
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t model-api:latest .

      - name: Load image into Minikube
        run: |
          minikube image load model-api:latest
          minikube image ls

      - name: Apply ConfigMap
        run: |
          kubectl apply -f K8s/config.yaml

      - name: Apply ServiceAccount
        run: |
          kubectl apply -f K8s/serviceaccount.yaml

      - name: Apply Deployment
        run: |
          kubectl apply -f K8s/deployment.yaml

      - name: Apply Service
        run: |
          kubectl apply -f K8s/service.yaml

      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/model-api --timeout=300s

      - name: Check Pod Statuses (Debugging)
        run: |
          kubectl get pods -l app=model-api
          kubectl describe deployment model-api
